
version: '3.1'

services:
  flaskapp:
    build: .
    # restart: always
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - ./server:/server
    ports:
      - "5000:5000"
    command: /bin/sh -c "cd /server && python app.py"
  mysql:
    image: mysql:latest
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
  adminer:
    image: adminer
    # restart: always
    ports:
      - "8080:8080"
  redis:
    image: redis:alpine
    # restart: always
    environment:
      - REDIS_PASS=example